apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
  - nodePort: 30442 # 302222
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: nginx
  type: NodePort # cluster - loadbalancer

# 3 types of svc - cluster-ip - NodePort - Loadbalancer 